### ISSUE TITLE
Adding levers causes type error

### ISSUE THREAD

**Issue by saschaishikawa** [Project-Platypus/Rhodium#1]
Is there a design reason I can't iteratively build `model.levers` and `model.responses` like the regular parameters list, i.e. `model.parameters += Parameter("nsamples")`

`TypeError: can only add <type 'type'> objects`

**Comment by dhadka** [comment]
Hi, this is fixed in commit https://github.com/Project-Platypus/Rhodium/commit/037adcf6b522f5f384dde43207150e331cabb174.
