### ISSUE TITLE
Issue using Jupyter Notebook with New Conda Environment

### ISSUE THREAD

**Issue by peterqstorm** [Project-Platypus/Rhodium#13]
When  using Jupyter Notebooks in a new Conda Environment (as to ensure I have Python 3.5), it defaults to using the system's Python version instead of the Conda environment. Thus, when trying to use Rhodium _et al._, the Jupyter Notebook examples aren't using the correct Python version (and its associated libraries).

If I install Jupyter Notebook in this new Conda Environment, it solves the issue of launching the correct Python version when opening a Jupyter Notebook within this Conda Environment.

**Comment by dhadka** [comment]
Rhodium and its dependencies now all support Python 3, so I think the issue here of combining Conda + Jupyter and Python versions should be fixed.
