### ISSUE TITLE
Add 'scikit-learn' to install_requires in setup.py

### ISSUE THREAD

**Issue by jackjackk** [Project-Platypus/Rhodium#2]
After installing Rhodium in a new venv, scikit-learn seems to be needed when importing everything.

Thanks

**Comment by peterqstorm** [comment]
I had the same exact issue.

When setting up the environment using a conda environment from scratch, I ran through the setup files as instructed. However, when attempting to use `from scipy.optimize import brentq as root`, I ran into the issue that sklearn wasn't installed.

I was able to install it using 'conda install scikit-learn' but wasn't sure if it was an issue on my end or with the automated setup files. 

Thanks!

**Comment by dhadka** [comment]
Fixed in pyproject.toml
