### ISSUE TITLE
Some questions on the reference materials. 

### ISSUE THREAD

**Issue by scalet98** [Project-Platypus/Rhodium#29]
Dear David Hadka,

Hello !
I try to reach to you through e-mail from research paper. 
But i could not reach you so I write this article here. 

Now I am using some component of your Rhodium and MORDM.
Therefore, I am studying on some theoretical stuffs and trying to figure out how to apply your tools in my model HSPF.
I think I can apply your tool If I am extracting some data from my model.
But I want to apply those tools directly in your open source based tools.
And I found some of your research papers. But I could not find some referenced file for your paper.
If you have one, could you share it with me?
The name of paper is as belows.

Ward, V., Hadka, D.M., Reed, P.M., 2015. Confronting Decision Cliffs: Diagnostic
Assessment of Multi-objective Evolutionary Algorithm Performance for
Addressing Uncertain Environmental Thresholds. Accepted to Environmental
Modelling & Software. 10.1016/j.envsoft.2015.07.020.

And Actually I found some other research paper on those topic. 
Do you think is this same research material? 
Could you confirm it? And the name of the research paper that I had found is as belows. 

Ward, V. L., Singh, R., Reed, P. M., & Keller, K. (2015). Confronting tipping points: Can multi-objective evolutionary algorithms discover pollution control tradeoffs given environmental thresholds?. Environmental Modelling & Software, 73, 27-43.

Thank you for reading my simple question.
-------------------------------------------
Ji-Heon Lee
E-mail : scalet98@chungbuk.ac.kr/ 
career03@hotmail.com

**Comment by dhadka** [comment]
Hi, not sure if it's still helpful given this was filed nearly a year ago, but yes, the referenced papers are related to this work.  Best best direct citation is https://par.nsf.gov/servlets/purl/10314245.
