### ISSUE TITLE
Cannot import Wrappers from Platypus

### ISSUE THREAD

**Issue by A-Spangler** [Project-Platypus/Rhodium#43]
Hello, 

I am running python v 3.11,  Rhodium v 1.2.0, and platypus v 1.1.0.  I have installed platypus with platypus-opt. 

In the Rhodium Lake problem example using Borg, the line `from platypus import wrappers` is not running successfully. Because of this, `output = optimize(model, "BorgMOEA", 20000, module="platypus.wrappers", epsilons=[0.01, 0.01, 0.0001, 0.0001])` returns an import error, where wrappers cannot be imported from Platypus. 

Do you have any suggestions on this?

**Comment by dhadka** [comment]
This might be too late to be of any help, but in case others find this issue...

BorgMOEA is closed source and not available in Platypus.  To get access:

1. Request access to the Borg MOEA at http://borgmoea.org/
2. Clone https://github.com/BorgMOEA/PyBorg
3. See `examples/rhodium_lake_problem.py`
