### ISSUE TITLE
Borg and parallel Borg

### ISSUE THREAD

**Issue by davidanthoff** [Project-Platypus/Rhodium#5]
I'm trying to understand whether this can work with Borg, or even parallel Borg?

**Comment by dhadka** [comment]
Hey David.  No, this can't interface directly with Borg or Parallel Borg.  Although you could technically run Borg to produce its output file and then load that output into Rhodium for further analysis.

I do have a pure Python implementation of (serial) Borg that can work with this library, but it's still experimental.  I'm happy to share it if you're interested.
